<a href="https://colab.research.google.com/github/wcjona/BMEN_415_Final_Project/blob/main/Classification_Models/SoosungByun%2030076800%3A%20Classification_Support_Vector_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Data Curation**

In [1]:
import pandas as pd

df = pd.read_csv("/content/Maternal Health Risk Data Set.csv")
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [2]:
df = df.drop_duplicates()
df = df.dropna()
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [3]:
df = df.replace({"low risk": 0, "mid risk":1, "high risk":2})
df.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86          2
1   35         140           90  13.0      98.0         70          2
2   29          90           70   8.0     100.0         80          2
3   30         140           85   7.0      98.0         70          2
4   35         120           60   6.1      98.0         76          0

In [4]:
from sklearn.model_selection import train_test_split
y = df["RiskLevel"]
x = df.loc[:,df.columns!="RiskLevel"]

x.head()

   Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
0   25         130           80  15.0      98.0         86
1   35         140           90  13.0      98.0         70
2   29          90           70   8.0     100.0         80
3   30         140           85   7.0      98.0         70
4   35         120           60   6.1      98.0         76

In [5]:
mean_std_x=(x-x.mean())/x.std()
mean_std_x.head()

        Age  SystolicBP  DiastolicBP        BS  BodyTemp  HeartRate
0 -0.304683    1.088104     0.333115  2.351833 -0.490807   1.477372
1  0.421671    1.647630     1.060146  1.644922 -0.490807  -0.484140
2 -0.014141   -1.149998    -0.393916 -0.122357  0.926731   0.741805
3  0.058494    1.647630     0.696631 -0.475812 -0.490807  -0.484140
4  0.421671    0.528578    -1.120946 -0.793922 -0.490807   0.251427

In [6]:
# Split training and test data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=142)

### **Support Vector Machine Classification**

In [7]:
# Importing necessary library
from sklearn.svm import SVC

# SVM classifier
SVM = SVC(kernel='linear')

# Training
SVM.fit(x_train, y_train)

# Prediction
y_pred = SVM.predict(x_test)

### **Evaluation**

In [8]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", round(accuracy*100,4))
print("Confusion Matrix:\n",cm)

# For confusion matrix, the rows correspond to y_test and the columns correspond to y_pred

Accuracy: 70.3297
Confusion Matrix:
 [[50  1  1]
 [15  0  4]
 [ 4  2 14]]